; bits.inc
; Copyright (c) 2004 Texas Instruments
;
; This package is free software;  you can redistribute it and/or
; modify it under the terms of the license found in the file
; named COPYING that should have accompanied this file.
;
; THIS PACKAGE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
; IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
; WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
;

BIT0  	EQU	(1<<0)
BIT1    EQU	(1<<1)
BIT2    EQU     (1<<2)
BIT3    EQU     (1<<3)
BIT4    EQU     (1<<4)
BIT5    EQU     (1<<5)
BIT6    EQU     (1<<6)
BIT7    EQU     (1<<7)
BIT8    EQU     (1<<8)
BIT9    EQU     (1<<9)
BIT10   EQU     (1<<10)
BIT11   EQU     (1<<11)
BIT12   EQU     (1<<12)
BIT13   EQU     (1<<13)
BIT14   EQU     (1<<14)
BIT15   EQU     (1<<15)
BIT16   EQU     (1<<16)
BIT17   EQU     (1<<17)
BIT18   EQU     (1<<18)
BIT19   EQU     (1<<19)
BIT20   EQU     (1<<20)
BIT21   EQU     (1<<21)
BIT22   EQU     (1<<22)
BIT23   EQU     (1<<23)
BIT24   EQU     (1<<24)
BIT25   EQU     (1<<25)
BIT26   EQU     (1<<26)
BIT27 	EQU     (1<<27)
BIT28 	EQU     (1<<28)
BIT29 	EQU     (1<<29)
BIT30 	EQU     (1<<30)
BIT31	EQU	(1<<31)

    END
